# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c53ad26c9ee614fce22ad9f99305acf84e30fed67ef55d5820620e32765c1e10b78f267067268769486d5b3f651e3c50a073e86abd526dfc0c9292a8c97e4946

test:
  secret_key_base: 420d34c2e075f5a96442f4a856762e225f7d1a75a776d058e55aa1ce511a62f3b38ce960db6782b33e007acad1069fd710b5290bf2e5b78138ef70ebb2622842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
